
;**************************************************************************
;* sci_gb60.inc - definice pro ovladac serioveho rozhrani
;**************************************************************************

BD4800      equ     4
BD9600      equ     9
BD19200     equ     19
BD38400     equ     38
BD57600     equ     57
BD115200    equ     115

            xref    sci1_init, sci1_out, sci1_in, sci1_str_out